-- PTSI Accounting — 08_comments.sql (ตัวเลือก)
-- บันทึกคำอธิบายภาษาไทยของทุกตาราง/คอลัมน์/view ลงใน PostgreSQL (COMMENT ON) — รันซ้ำได้ ไม่กระทบข้อมูล
-- รันด้วย acct_owner:  psql -U acct_owner -d ptsi_accounting -f 08_comments.sql
SET search_path TO acct, public;

COMMENT ON TABLE acct.accounting_periods IS 'งวดบัญชีรายเดือน — งวด CLOSED ห้ามลงบัญชีวันที่ในเดือนนั้น (trigger fn_period_guard)';
COMMENT ON COLUMN acct.accounting_periods.period_ym IS 'งวด รูปแบบ YYYY-MM (PK)';
COMMENT ON COLUMN acct.accounting_periods.status IS 'OPEN / CLOSED';
COMMENT ON COLUMN acct.accounting_periods.closed_by IS 'ผู้ปิดงวด';
COMMENT ON COLUMN acct.accounting_periods.closed_at IS 'เวลาที่ปิดงวด';
COMMENT ON COLUMN acct.accounting_periods.reopened_by IS 'ผู้เปิดงวดซ้ำ (เฉพาะ ADMIN)';
COMMENT ON COLUMN acct.accounting_periods.reopened_at IS 'เวลาที่เปิดงวดซ้ำ';
COMMENT ON COLUMN acct.accounting_periods.remark IS 'หมายเหตุ';
COMMENT ON TABLE acct.app_session IS 'session ของผู้ใช้ที่ login แล้ว — token สุ่ม 32 ไบต์ หมดอายุตาม setting.session_hours';
COMMENT ON COLUMN acct.app_session.token IS 'token ของ session (hex 64 ตัว) ใช้เป็น Bearer token';
COMMENT ON COLUMN acct.app_session.user_id IS 'ผู้ใช้ (→ app_user)';
COMMENT ON COLUMN acct.app_session.created_at IS 'เวลาที่สร้างรายการ';
COMMENT ON COLUMN acct.app_session.expires_at IS 'เวลาหมดอายุ (created_at + setting.session_hours)';
COMMENT ON COLUMN acct.app_session.client_ip IS 'IP ของผู้ login';
COMMENT ON TABLE acct.app_user IS 'ผู้ใช้งานระบบ — รหัสผ่านเก็บแบบ bcrypt (pgcrypto crypt/gen_salt)';
COMMENT ON COLUMN acct.app_user.user_id IS 'รหัส (Primary Key)';
COMMENT ON COLUMN acct.app_user.username IS 'ชื่อผู้ใช้ (ห้ามซ้ำ)';
COMMENT ON COLUMN acct.app_user.full_name IS 'ชื่อ-นามสกุล';
COMMENT ON COLUMN acct.app_user.role_code IS 'บทบาท (ADMIN / ACCOUNTANT / SALES / VIEWER)';
COMMENT ON COLUMN acct.app_user.password_hash IS 'รหัสผ่านแบบ bcrypt (crypt/gen_salt bf)';
COMMENT ON COLUMN acct.app_user.active IS 'บัญชีใช้งานได้หรือไม่';
COMMENT ON COLUMN acct.app_user.last_login_at IS 'เวลา login ล่าสุด';
COMMENT ON COLUMN acct.app_user.created_at IS 'เวลาที่สร้างรายการ';
COMMENT ON TABLE acct.audit_log IS 'บันทึกการเปลี่ยนแปลงข้อมูล (audit trail) แบบ generic — เก็บแถวเก่า/ใหม่เป็น JSON';
COMMENT ON COLUMN acct.audit_log.audit_id IS 'รหัส (PK)';
COMMENT ON COLUMN acct.audit_log.table_name IS 'ตารางที่ถูกแก้ไข';
COMMENT ON COLUMN acct.audit_log.row_pk IS 'ค่า PK ของแถวที่ถูกแก้';
COMMENT ON COLUMN acct.audit_log.action IS 'INSERT / UPDATE / DELETE';
COMMENT ON COLUMN acct.audit_log.changed_at IS 'เวลาที่เปลี่ยน';
COMMENT ON COLUMN acct.audit_log.changed_by IS 'ผู้ทำรายการ (จาก acct.audit_user หรือ updated_by/created_by)';
COMMENT ON COLUMN acct.audit_log.old_data IS 'ข้อมูลก่อนเปลี่ยน (JSON)';
COMMENT ON COLUMN acct.audit_log.new_data IS 'ข้อมูลหลังเปลี่ยน (JSON)';
COMMENT ON TABLE acct.banks IS 'ข้อมูลหลักธนาคาร — ใช้เป็น dropdown ทุกช่อง "ธนาคาร" (เพิ่ม/ปิดใช้งานได้จาก Master Data)';
COMMENT ON COLUMN acct.banks.bank_id IS 'รหัสธนาคาร (PK)';
COMMENT ON COLUMN acct.banks.bank_code IS 'รหัสย่อธนาคาร (ห้ามซ้ำ)';
COMMENT ON COLUMN acct.banks.bank_name IS 'ชื่อธนาคาร';
COMMENT ON COLUMN acct.banks.sort_order IS 'ลำดับการแสดงผล';
COMMENT ON COLUMN acct.banks.is_active IS 'ใช้งานอยู่ (false = ปิดใช้งาน ไม่แสดงในรายการเลือก)';
COMMENT ON COLUMN acct.banks.created_at IS 'เวลาที่สร้างรายการ';
COMMENT ON COLUMN acct.banks.created_by IS 'ผู้สร้างรายการ (username)';
COMMENT ON COLUMN acct.banks.updated_at IS 'เวลาที่แก้ไขล่าสุด';
COMMENT ON COLUMN acct.banks.updated_by IS 'ผู้แก้ไขล่าสุด (username)';
COMMENT ON TABLE acct.billing_note_items IS 'รายการใบแจ้งหนี้ที่รวมอยู่ในใบวางบิล';
COMMENT ON COLUMN acct.billing_note_items.billing_note_item_id IS 'รหัส (Primary Key)';
COMMENT ON COLUMN acct.billing_note_items.billing_note_id IS 'อ้างอิง → billing_notes';
COMMENT ON COLUMN acct.billing_note_items.invoice_id IS 'อ้างอิง → invoices';
COMMENT ON COLUMN acct.billing_note_items.amount IS 'ยอดของใบแจ้งหนี้ที่วางบิล';
COMMENT ON TABLE acct.billing_notes IS 'ใบวางบิล — รวมหลายใบแจ้งหนี้ของลูกค้ารายเดียวกันเพื่อเรียกเก็บพร้อมกัน';
COMMENT ON COLUMN acct.billing_notes.billing_note_id IS 'รหัส (Primary Key)';
COMMENT ON COLUMN acct.billing_notes.billing_note_no IS 'เลขที่ใบวางบิล BN-YYYYMMDD-NNNNN';
COMMENT ON COLUMN acct.billing_notes.billing_date IS 'วันที่วางบิล';
COMMENT ON COLUMN acct.billing_notes.customer_id IS 'อ้างอิง → customers';
COMMENT ON COLUMN acct.billing_notes.due_date IS 'วันครบกำหนดชำระ';
COMMENT ON COLUMN acct.billing_notes.status IS 'OPEN / CLOSED / CANCELLED';
COMMENT ON COLUMN acct.billing_notes.total_amount IS 'ยอดรวมใบแจ้งหนี้ทั้งหมดที่วางบิล';
COMMENT ON COLUMN acct.billing_notes.signature_mode IS 'โหมดลายเซ็นบนเอกสารพิมพ์: BLANK = เว้นว่าง, DIGITAL = ใส่ลายเซ็นดิจิทัล';
COMMENT ON COLUMN acct.billing_notes.created_at IS 'เวลาที่สร้างรายการ';
COMMENT ON COLUMN acct.billing_notes.created_by IS 'ผู้สร้างรายการ (username)';
COMMENT ON COLUMN acct.billing_notes.updated_at IS 'เวลาที่แก้ไขล่าสุด';
COMMENT ON COLUMN acct.billing_notes.updated_by IS 'ผู้แก้ไขล่าสุด (username)';
COMMENT ON TABLE acct.cash_entries IS 'สมุดเงินสดรายวัน — รายรับ/รายจ่าย/ค่าหุ้น ลงบัญชีอัตโนมัติ';
COMMENT ON COLUMN acct.cash_entries.entry_id IS 'รหัส (Primary Key)';
COMMENT ON COLUMN acct.cash_entries.entry_no IS 'เลขที่ CB-YYYYMMDD-NNNNN';
COMMENT ON COLUMN acct.cash_entries.entry_date IS 'วันที่รายการ';
COMMENT ON COLUMN acct.cash_entries.direction IS 'IN = รับ, OUT = จ่าย';
COMMENT ON COLUMN acct.cash_entries.entry_type IS 'GENERAL = รายการทั่วไป, SHARE_CAPITAL = ค่าหุ้น';
COMMENT ON COLUMN acct.cash_entries.shareholder_id IS 'ผู้ถือหุ้น (เฉพาะรายการค่าหุ้น)';
COMMENT ON COLUMN acct.cash_entries.account_id IS 'บัญชีคู่ (ไม่ใช่เงินสด/ธนาคาร)';
COMMENT ON COLUMN acct.cash_entries.counterparty IS 'คู่รายการ (ผู้รับ/ผู้จ่ายเงิน)';
COMMENT ON COLUMN acct.cash_entries.description IS 'รายละเอียด';
COMMENT ON COLUMN acct.cash_entries.amount IS 'ยอดเงินรวมในบิล (รวม VAT)';
COMMENT ON COLUMN acct.cash_entries.payment_method IS 'CASH / TRANSFER / CHEQUE';
COMMENT ON COLUMN acct.cash_entries.ref_no IS 'เลขที่อ้างอิง';
COMMENT ON COLUMN acct.cash_entries.bank_name IS 'ชื่อธนาคาร (ข้อความ — เลือกจาก Master Data → Banks)';
COMMENT ON COLUMN acct.cash_entries.remark IS 'หมายเหตุ';
COMMENT ON COLUMN acct.cash_entries.status IS 'ACTIVE / VOID';
COMMENT ON COLUMN acct.cash_entries.void_reason IS 'เหตุผลที่ยกเลิกเอกสาร';
COMMENT ON COLUMN acct.cash_entries.journal_id IS 'journal ที่ลงบัญชีของเอกสารนี้';
COMMENT ON COLUMN acct.cash_entries.reversal_journal_id IS 'journal กลับรายการ (เมื่อยกเลิกเอกสารที่ลงบัญชีแล้ว)';
COMMENT ON COLUMN acct.cash_entries.created_at IS 'เวลาที่สร้างรายการ';
COMMENT ON COLUMN acct.cash_entries.created_by IS 'ผู้สร้างรายการ (username)';
COMMENT ON COLUMN acct.cash_entries.updated_at IS 'เวลาที่แก้ไขล่าสุด';
COMMENT ON COLUMN acct.cash_entries.updated_by IS 'ผู้แก้ไขล่าสุด (username)';
COMMENT ON COLUMN acct.cash_entries.vat_amount IS 'VAT ในบิล (ขอคืนภาษีซื้อ — เฉพาะรายจ่ายทั่วไป)';
COMMENT ON COLUMN acct.cash_entries.counterparty_tax_id IS 'เลขผู้เสียภาษีของคู่รายการ (สำหรับรายงานภาษีซื้อ)';
COMMENT ON TABLE acct.chart_of_account_details IS 'ผังบัญชี — รองรับบัญชีย่อยผ่าน parent_account_id';
COMMENT ON COLUMN acct.chart_of_account_details.account_id IS 'รหัสบัญชี (PK)';
COMMENT ON COLUMN acct.chart_of_account_details.account_code IS 'เลขที่บัญชี (ห้ามซ้ำ)';
COMMENT ON COLUMN acct.chart_of_account_details.account_name IS 'ชื่อบัญชี';
COMMENT ON COLUMN acct.chart_of_account_details.parent_account_id IS 'บัญชีแม่ (บัญชีย่อย)';
COMMENT ON COLUMN acct.chart_of_account_details.category_id IS 'หมวดบัญชีหลัก (→ chart_of_account_master)';
COMMENT ON COLUMN acct.chart_of_account_details.created_at IS 'เวลาที่สร้างรายการ';
COMMENT ON COLUMN acct.chart_of_account_details.created_by IS 'ผู้สร้างรายการ (username)';
COMMENT ON COLUMN acct.chart_of_account_details.updated_at IS 'เวลาที่แก้ไขล่าสุด';
COMMENT ON COLUMN acct.chart_of_account_details.updated_by IS 'ผู้แก้ไขล่าสุด (username)';
COMMENT ON COLUMN acct.chart_of_account_details.is_active IS 'ใช้งานอยู่ (false = ปิดใช้งาน ไม่แสดงในรายการเลือก)';
COMMENT ON TABLE acct.chart_of_account_master IS 'หมวดบัญชีหลัก 5 หมวด (สินทรัพย์ หนี้สิน ส่วนของผู้ถือหุ้น รายได้ ค่าใช้จ่าย)';
COMMENT ON COLUMN acct.chart_of_account_master.category_id IS 'รหัสหมวด (PK)';
COMMENT ON COLUMN acct.chart_of_account_master.category_code IS 'ASSET / LIABILITY / EQUITY / REVENUE / EXPENSE';
COMMENT ON COLUMN acct.chart_of_account_master.category_name_th IS 'ชื่อหมวด (ไทย)';
COMMENT ON COLUMN acct.chart_of_account_master.category_name_en IS 'ชื่อหมวด (อังกฤษ)';
COMMENT ON COLUMN acct.chart_of_account_master.display_order IS 'ลำดับแสดงในงบ';
COMMENT ON COLUMN acct.chart_of_account_master.is_active IS 'ใช้งานอยู่ (false = ปิดใช้งาน ไม่แสดงในรายการเลือก)';
COMMENT ON TABLE acct.company_profile IS 'ข้อมูลบริษัทของเราเอง (ผู้ออกเอกสาร) — มีแถวเดียว, เก็บตราประทับบริษัทเป็นรูปภาพ';
COMMENT ON COLUMN acct.company_profile.company_id IS 'รหัสบริษัท (PK)';
COMMENT ON COLUMN acct.company_profile.company_name_th IS 'ชื่อบริษัท (ไทย)';
COMMENT ON COLUMN acct.company_profile.company_name_en IS 'ชื่อบริษัท (อังกฤษ)';
COMMENT ON COLUMN acct.company_profile.tax_id IS 'เลขประจำตัวผู้เสียภาษี (13 หลัก)';
COMMENT ON COLUMN acct.company_profile.branch_no IS 'รหัสสาขา (0000 = สำนักงานใหญ่)';
COMMENT ON COLUMN acct.company_profile.address IS 'ที่อยู่ (ไทย) เลขที่ หมู่ ซอย ถนน';
COMMENT ON COLUMN acct.company_profile.address_en IS 'ที่อยู่ (อังกฤษ)';
COMMENT ON COLUMN acct.company_profile.subdistrict_id IS 'ตำบล/แขวง (→ th_subdistrict) — อำเภอ จังหวัดอ้างอิงต่อจากตำบล';
COMMENT ON COLUMN acct.company_profile.zip_code IS 'รหัสไปรษณีย์';
COMMENT ON COLUMN acct.company_profile.registered_capital IS 'ทุนจดทะเบียน';
COMMENT ON COLUMN acct.company_profile.share_count IS 'จำนวนหุ้นทั้งหมด';
COMMENT ON COLUMN acct.company_profile.share_value IS 'มูลค่าหุ้นต่อหุ้น';
COMMENT ON COLUMN acct.company_profile.company_stamp_image IS 'ภาพตราประทับบริษัท (bytea)';
COMMENT ON COLUMN acct.company_profile.company_stamp_filename IS 'ชื่อไฟล์ตราประทับ';
COMMENT ON COLUMN acct.company_profile.company_stamp_mime IS 'ชนิดไฟล์ตราประทับ';
COMMENT ON COLUMN acct.company_profile.company_stamp_updated_date IS 'วันที่อัปเดตตราประทับ';
COMMENT ON COLUMN acct.company_profile.created_at IS 'เวลาที่สร้างรายการ';
COMMENT ON COLUMN acct.company_profile.created_by IS 'ผู้สร้างรายการ (username)';
COMMENT ON COLUMN acct.company_profile.updated_at IS 'เวลาที่แก้ไขล่าสุด';
COMMENT ON COLUMN acct.company_profile.updated_by IS 'ผู้แก้ไขล่าสุด (username)';
COMMENT ON COLUMN acct.company_profile.phone IS 'โทรศัพท์';
COMMENT ON COLUMN acct.company_profile.email IS 'อีเมล';
COMMENT ON TABLE acct.credit_notes IS 'ใบลดหนี้ขาย — ลดยอดใบแจ้งหนี้ที่ลงบัญชีแล้ว';
COMMENT ON COLUMN acct.credit_notes.cn_id IS 'รหัสใบลดหนี้ (PK)';
COMMENT ON COLUMN acct.credit_notes.cn_no IS 'เลขที่ CN-YYYYMMDD-NNNNN';
COMMENT ON COLUMN acct.credit_notes.cn_date IS 'วันที่ใบลดหนี้';
COMMENT ON COLUMN acct.credit_notes.invoice_id IS 'ใบแจ้งหนี้ที่ลดหนี้ (→ invoices)';
COMMENT ON COLUMN acct.credit_notes.customer_id IS 'อ้างอิง → customers';
COMMENT ON COLUMN acct.credit_notes.reason IS 'เหตุผล';
COMMENT ON COLUMN acct.credit_notes.revenue_account_id IS 'บัญชีรายได้ (→ chart_of_account_details)';
COMMENT ON COLUMN acct.credit_notes.subtotal IS 'มูลค่าที่ลดก่อน VAT';
COMMENT ON COLUMN acct.credit_notes.vat_rate IS 'อัตรา VAT (%)';
COMMENT ON COLUMN acct.credit_notes.vat_amount IS 'จำนวนเงินภาษีมูลค่าเพิ่ม';
COMMENT ON COLUMN acct.credit_notes.total_amount IS 'ยอดรวมสุทธิ (รวม VAT)';
COMMENT ON COLUMN acct.credit_notes.status IS 'ACTIVE / VOID';
COMMENT ON COLUMN acct.credit_notes.void_reason IS 'เหตุผลที่ยกเลิกเอกสาร';
COMMENT ON COLUMN acct.credit_notes.posted_flag IS 'ลงบัญชี (Post to GL) แล้วหรือยัง';
COMMENT ON COLUMN acct.credit_notes.journal_id IS 'journal ที่ลงบัญชีของเอกสารนี้';
COMMENT ON COLUMN acct.credit_notes.reversal_journal_id IS 'journal กลับรายการ (เมื่อยกเลิกเอกสารที่ลงบัญชีแล้ว)';
COMMENT ON COLUMN acct.credit_notes.signature_mode IS 'โหมดลายเซ็นบนเอกสารพิมพ์: BLANK = เว้นว่าง, DIGITAL = ใส่ลายเซ็นดิจิทัล';
COMMENT ON COLUMN acct.credit_notes.remark IS 'หมายเหตุ';
COMMENT ON COLUMN acct.credit_notes.created_at IS 'เวลาที่สร้างรายการ';
COMMENT ON COLUMN acct.credit_notes.created_by IS 'ผู้สร้างรายการ (username)';
COMMENT ON COLUMN acct.credit_notes.updated_at IS 'เวลาที่แก้ไขล่าสุด';
COMMENT ON COLUMN acct.credit_notes.updated_by IS 'ผู้แก้ไขล่าสุด (username)';
COMMENT ON TABLE acct.customers IS 'ลูกค้า — ฝั่งขาย (AR)';
COMMENT ON COLUMN acct.customers.customer_id IS 'รหัสลูกค้า (PK)';
COMMENT ON COLUMN acct.customers.customer_code IS 'รหัสลูกค้า (ห้ามซ้ำ) เช่น CUST-0001';
COMMENT ON COLUMN acct.customers.customer_name_th IS 'ชื่อลูกค้า (ไทย)';
COMMENT ON COLUMN acct.customers.customer_name_en IS 'ชื่อลูกค้า (อังกฤษ)';
COMMENT ON COLUMN acct.customers.tax_id IS 'เลขประจำตัวผู้เสียภาษี (13 หลัก)';
COMMENT ON COLUMN acct.customers.branch_no IS 'รหัสสาขา (0000 = สำนักงานใหญ่)';
COMMENT ON COLUMN acct.customers.address IS 'ที่อยู่ (ไทย) เลขที่ หมู่ ซอย ถนน';
COMMENT ON COLUMN acct.customers.address_en IS 'ที่อยู่ (อังกฤษ)';
COMMENT ON COLUMN acct.customers.subdistrict_id IS 'ตำบล/แขวง (→ th_subdistrict) — อำเภอ จังหวัดอ้างอิงต่อจากตำบล';
COMMENT ON COLUMN acct.customers.zip_code IS 'รหัสไปรษณีย์';
COMMENT ON COLUMN acct.customers.credit_term_days IS 'เครดิตเทอม (วัน) — ใช้คำนวณวันครบกำหนด';
COMMENT ON COLUMN acct.customers.created_at IS 'เวลาที่สร้างรายการ';
COMMENT ON COLUMN acct.customers.created_by IS 'ผู้สร้างรายการ (username)';
COMMENT ON COLUMN acct.customers.updated_at IS 'เวลาที่แก้ไขล่าสุด';
COMMENT ON COLUMN acct.customers.updated_by IS 'ผู้แก้ไขล่าสุด (username)';
COMMENT ON COLUMN acct.customers.phone IS 'โทรศัพท์';
COMMENT ON COLUMN acct.customers.email IS 'อีเมล';
COMMENT ON COLUMN acct.customers.contact_person IS 'ผู้ติดต่อ';
COMMENT ON COLUMN acct.customers.is_active IS 'ใช้งานอยู่ (false = ปิดใช้งาน ไม่แสดงในรายการเลือก)';
COMMENT ON TABLE acct.delivery_note_items IS 'รายการสินค้าในใบส่งของ';
COMMENT ON COLUMN acct.delivery_note_items.delivery_note_item_id IS 'รหัส (Primary Key)';
COMMENT ON COLUMN acct.delivery_note_items.delivery_note_id IS 'อ้างอิง → delivery_notes';
COMMENT ON COLUMN acct.delivery_note_items.item_id IS 'อ้างอิง → items';
COMMENT ON COLUMN acct.delivery_note_items.qty IS 'จำนวนที่ส่ง';
COMMENT ON TABLE acct.delivery_notes IS 'ใบส่งของ';
COMMENT ON COLUMN acct.delivery_notes.delivery_note_id IS 'รหัส (Primary Key)';
COMMENT ON COLUMN acct.delivery_notes.delivery_note_no IS 'เลขที่ใบส่งของ';
COMMENT ON COLUMN acct.delivery_notes.delivery_date IS 'วันที่ส่งของ/กำหนดส่ง';
COMMENT ON COLUMN acct.delivery_notes.customer_id IS 'อ้างอิง → customers';
COMMENT ON COLUMN acct.delivery_notes.quotation_id IS 'ใบเสนอราคาต้นทาง';
COMMENT ON COLUMN acct.delivery_notes.status IS 'DRAFT / DELIVERED / CANCELLED';
COMMENT ON COLUMN acct.delivery_notes.signature_mode IS 'โหมดลายเซ็นบนเอกสารพิมพ์: BLANK = เว้นว่าง, DIGITAL = ใส่ลายเซ็นดิจิทัล';
COMMENT ON COLUMN acct.delivery_notes.created_at IS 'เวลาที่สร้างรายการ';
COMMENT ON COLUMN acct.delivery_notes.created_by IS 'ผู้สร้างรายการ (username)';
COMMENT ON COLUMN acct.delivery_notes.updated_at IS 'เวลาที่แก้ไขล่าสุด';
COMMENT ON COLUMN acct.delivery_notes.updated_by IS 'ผู้แก้ไขล่าสุด (username)';
COMMENT ON TABLE acct.doc_files IS 'ไฟล์แนบของเอกสาร (ใช้งานจริง) — แนบกับ 14 ประเภทเอกสาร เก็บเป็น bytea ลบแบบ soft delete';
COMMENT ON COLUMN acct.doc_files.attachment_id IS 'รหัส (Primary Key)';
COMMENT ON COLUMN acct.doc_files.doc_type IS 'ประเภทเอกสาร: quotation, delivery, invoice, billing, receipt, pr, po, vi, vp, wht, cb, cn, vcn, gr';
COMMENT ON COLUMN acct.doc_files.doc_id IS 'รหัสเอกสารที่แนบ';
COMMENT ON COLUMN acct.doc_files.category IS 'หมวดไฟล์แนบ';
COMMENT ON COLUMN acct.doc_files.file_name IS 'ชื่อไฟล์';
COMMENT ON COLUMN acct.doc_files.mime_type IS 'ชนิดไฟล์ (MIME)';
COMMENT ON COLUMN acct.doc_files.file_size IS 'ขนาดไฟล์ (ไบต์ — จำกัด 4 MB)';
COMMENT ON COLUMN acct.doc_files.file_data IS 'เนื้อไฟล์ (bytea)';
COMMENT ON COLUMN acct.doc_files.note IS 'บันทึกประกอบ';
COMMENT ON COLUMN acct.doc_files.uploaded_by IS 'ผู้อัปโหลด';
COMMENT ON COLUMN acct.doc_files.uploaded_at IS 'เวลาที่อัปโหลด';
COMMENT ON COLUMN acct.doc_files.is_deleted IS 'ลบแล้ว (soft delete)';
COMMENT ON COLUMN acct.doc_files.deleted_by IS 'ผู้ลบ';
COMMENT ON COLUMN acct.doc_files.deleted_at IS 'เวลาที่ลบ';
COMMENT ON TABLE acct.document_attachments IS 'ตารางไฟล์แนบเดิมจาก Oracle APEX — ไม่ได้ใช้งานแล้ว (แทนด้วย doc_files)';
COMMENT ON COLUMN acct.document_attachments.attachment_id IS 'รหัส (Primary Key)';
COMMENT ON COLUMN acct.document_attachments.module_name IS 'โมดูล (เดิมจาก APEX)';
COMMENT ON COLUMN acct.document_attachments.ref_table IS 'ตารางอ้างอิง';
COMMENT ON COLUMN acct.document_attachments.ref_id IS 'รหัสแถวอ้างอิง';
COMMENT ON COLUMN acct.document_attachments.doc_category IS 'หมวดไฟล์';
COMMENT ON COLUMN acct.document_attachments.file_name IS 'ชื่อไฟล์';
COMMENT ON COLUMN acct.document_attachments.file_mime_type IS 'ชนิดไฟล์';
COMMENT ON COLUMN acct.document_attachments.file_content IS 'เนื้อไฟล์';
COMMENT ON COLUMN acct.document_attachments.uploaded_by IS 'ผู้อัปโหลด';
COMMENT ON COLUMN acct.document_attachments.uploaded_date IS 'วันที่อัปโหลด';
COMMENT ON TABLE acct.employees IS 'พนักงาน — ใช้เป็นผู้ขาย (salesperson), ผู้ขอซื้อ/ผู้อนุมัติ, ผู้ลงนามเอกสาร (เก็บภาพลายเซ็น)';
COMMENT ON COLUMN acct.employees.employee_id IS 'รหัส (Primary Key)';
COMMENT ON COLUMN acct.employees.employee_code IS 'รหัสพนักงาน';
COMMENT ON COLUMN acct.employees.first_name_th IS 'ชื่อ (ไทย)';
COMMENT ON COLUMN acct.employees.last_name_th IS 'นามสกุล (ไทย)';
COMMENT ON COLUMN acct.employees.first_name_en IS 'ชื่อ (อังกฤษ)';
COMMENT ON COLUMN acct.employees.last_name_en IS 'นามสกุล (อังกฤษ)';
COMMENT ON COLUMN acct.employees.position IS 'ตำแหน่ง';
COMMENT ON COLUMN acct.employees.department IS 'แผนก';
COMMENT ON COLUMN acct.employees.signature_image IS 'ภาพลายเซ็น (bytea)';
COMMENT ON COLUMN acct.employees.signature_filename IS 'ชื่อไฟล์ลายเซ็น';
COMMENT ON COLUMN acct.employees.signature_mime_type IS 'ชนิดไฟล์ลายเซ็น';
COMMENT ON COLUMN acct.employees.signature_updated_date IS 'วันที่อัปเดตลายเซ็น';
COMMENT ON COLUMN acct.employees.created_at IS 'เวลาที่สร้างรายการ';
COMMENT ON COLUMN acct.employees.created_by IS 'ผู้สร้างรายการ (username)';
COMMENT ON COLUMN acct.employees.updated_at IS 'เวลาที่แก้ไขล่าสุด';
COMMENT ON COLUMN acct.employees.updated_by IS 'ผู้แก้ไขล่าสุด (username)';
COMMENT ON COLUMN acct.employees.email IS 'อีเมล';
COMMENT ON COLUMN acct.employees.is_active IS 'ใช้งานอยู่ (false = ปิดใช้งาน ไม่แสดงในรายการเลือก)';
COMMENT ON TABLE acct.goods_receipts IS 'ใบรับสินค้า (GR) — บันทึกการรับสินค้าตาม PO';
COMMENT ON COLUMN acct.goods_receipts.gr_id IS 'รหัส (Primary Key)';
COMMENT ON COLUMN acct.goods_receipts.gr_no IS 'เลขที่ GR-YYYYMMDD-NNNNN';
COMMENT ON COLUMN acct.goods_receipts.gr_date IS 'วันที่รับสินค้า';
COMMENT ON COLUMN acct.goods_receipts.po_id IS 'ใบสั่งซื้อที่รับ';
COMMENT ON COLUMN acct.goods_receipts.vendor_id IS 'อ้างอิง → vendors';
COMMENT ON COLUMN acct.goods_receipts.delivery_note_no IS 'เลขที่ใบส่งของของผู้ขาย';
COMMENT ON COLUMN acct.goods_receipts.vi_id IS 'ใบแจ้งหนี้ผู้ขายที่ผูก (ถ้ามี)';
COMMENT ON COLUMN acct.goods_receipts.status IS 'ACTIVE / VOID';
COMMENT ON COLUMN acct.goods_receipts.void_reason IS 'เหตุผลที่ยกเลิกเอกสาร';
COMMENT ON COLUMN acct.goods_receipts.remark IS 'หมายเหตุ';
COMMENT ON COLUMN acct.goods_receipts.signature_mode IS 'โหมดลายเซ็นบนเอกสารพิมพ์: BLANK = เว้นว่าง, DIGITAL = ใส่ลายเซ็นดิจิทัล';
COMMENT ON COLUMN acct.goods_receipts.created_at IS 'เวลาที่สร้างรายการ';
COMMENT ON COLUMN acct.goods_receipts.created_by IS 'ผู้สร้างรายการ (username)';
COMMENT ON COLUMN acct.goods_receipts.updated_at IS 'เวลาที่แก้ไขล่าสุด';
COMMENT ON COLUMN acct.goods_receipts.updated_by IS 'ผู้แก้ไขล่าสุด (username)';
COMMENT ON TABLE acct.gr_items IS 'รายการที่รับในใบรับสินค้า';
COMMENT ON COLUMN acct.gr_items.gr_item_id IS 'รหัส (Primary Key)';
COMMENT ON COLUMN acct.gr_items.gr_id IS 'อ้างอิง → goods_receipts';
COMMENT ON COLUMN acct.gr_items.po_item_id IS 'รายการใน PO ที่รับ (→ po_items)';
COMMENT ON COLUMN acct.gr_items.qty_received IS 'จำนวนที่รับ';
COMMENT ON TABLE acct.invoice_items IS 'รายการสินค้า/บริการในใบแจ้งหนี้';
COMMENT ON COLUMN acct.invoice_items.invoice_item_id IS 'รหัสรายการ (PK)';
COMMENT ON COLUMN acct.invoice_items.invoice_id IS 'อ้างอิง → invoices';
COMMENT ON COLUMN acct.invoice_items.item_id IS 'อ้างอิง → items';
COMMENT ON COLUMN acct.invoice_items.qty IS 'จำนวน';
COMMENT ON COLUMN acct.invoice_items.unit_price IS 'ราคาต่อหน่วย';
COMMENT ON COLUMN acct.invoice_items.amount IS 'qty × unit_price';
COMMENT ON TABLE acct.invoices IS 'ใบแจ้งหนี้/ใบกำกับภาษี — posted_flag = true เมื่อลงบัญชีแล้ว';
COMMENT ON COLUMN acct.invoices.invoice_id IS 'รหัส (Primary Key)';
COMMENT ON COLUMN acct.invoices.invoice_no IS 'เลขที่ INV-YYYYMMDD-NNNNN';
COMMENT ON COLUMN acct.invoices.invoice_date IS 'วันที่ใบแจ้งหนี้';
COMMENT ON COLUMN acct.invoices.customer_id IS 'อ้างอิง → customers';
COMMENT ON COLUMN acct.invoices.quotation_id IS 'ใบเสนอราคาต้นทาง';
COMMENT ON COLUMN acct.invoices.delivery_note_id IS 'ใบส่งของอ้างอิง';
COMMENT ON COLUMN acct.invoices.customer_po_no IS 'เลขที่ใบสั่งซื้อของลูกค้า';
COMMENT ON COLUMN acct.invoices.customer_po_date IS 'วันที่ใบสั่งซื้อของลูกค้า';
COMMENT ON COLUMN acct.invoices.due_date IS 'วันครบกำหนดชำระ';
COMMENT ON COLUMN acct.invoices.status IS 'UNPAID / PARTIAL / PAID / VOID';
COMMENT ON COLUMN acct.invoices.tax_invoice_no IS 'เลขที่ใบกำกับภาษี (กรอกเองตามกฎหมาย)';
COMMENT ON COLUMN acct.invoices.tax_invoice_date IS 'วันที่ใบกำกับภาษี';
COMMENT ON COLUMN acct.invoices.payment_term_text IS 'เงื่อนไขการชำระเงิน (ข้อความ)';
COMMENT ON COLUMN acct.invoices.vat_amount IS 'จำนวนเงินภาษีมูลค่าเพิ่ม';
COMMENT ON COLUMN acct.invoices.total_amount IS 'ยอดรวมสุทธิ (รวม VAT)';
COMMENT ON COLUMN acct.invoices.posted_flag IS 'ลงบัญชี (Post to GL) แล้วหรือยัง';
COMMENT ON COLUMN acct.invoices.signature_mode IS 'โหมดลายเซ็นบนเอกสารพิมพ์: BLANK = เว้นว่าง, DIGITAL = ใส่ลายเซ็นดิจิทัล';
COMMENT ON COLUMN acct.invoices.created_at IS 'เวลาที่สร้างรายการ';
COMMENT ON COLUMN acct.invoices.created_by IS 'ผู้สร้างรายการ (username)';
COMMENT ON COLUMN acct.invoices.updated_at IS 'เวลาที่แก้ไขล่าสุด';
COMMENT ON COLUMN acct.invoices.updated_by IS 'ผู้แก้ไขล่าสุด (username)';
COMMENT ON TABLE acct.item_categories IS 'หมวดหมู่สินค้า/บริการ (ระดับบน)';
COMMENT ON COLUMN acct.item_categories.category_id IS 'รหัส (Primary Key)';
COMMENT ON COLUMN acct.item_categories.category_name IS 'ชื่อหมวดหมู่';
COMMENT ON COLUMN acct.item_categories.category_code IS 'รหัสหมวด';
COMMENT ON COLUMN acct.item_categories.category_name_en IS 'category name en';
COMMENT ON COLUMN acct.item_categories.display_order IS 'display order';
COMMENT ON COLUMN acct.item_categories.is_active IS 'ใช้งานอยู่ (false = ปิดใช้งาน ไม่แสดงในรายการเลือก)';
COMMENT ON TABLE acct.item_name_standards IS 'ชื่อรายการมาตรฐานตามหมวดย่อย (LOV ของช่องชื่อสินค้า) — ย้ายมาจาก APEX';
COMMENT ON COLUMN acct.item_name_standards.standard_id IS 'รหัส (PK)';
COMMENT ON COLUMN acct.item_name_standards.subcategory_id IS 'อ้างอิง → item_subcategories';
COMMENT ON COLUMN acct.item_name_standards.item_name IS 'ชื่อรายการมาตรฐาน';
COMMENT ON COLUMN acct.item_name_standards.display_order IS 'ลำดับแสดงผล';
COMMENT ON COLUMN acct.item_name_standards.is_active IS 'ใช้งานอยู่ (false = ปิดใช้งาน ไม่แสดงในรายการเลือก)';
COMMENT ON TABLE acct.item_subcategories IS 'หมวดหมู่สินค้า/บริการ (ระดับย่อย)';
COMMENT ON COLUMN acct.item_subcategories.subcategory_id IS 'รหัส (Primary Key)';
COMMENT ON COLUMN acct.item_subcategories.category_id IS 'หมวด (FK)';
COMMENT ON COLUMN acct.item_subcategories.subcategory_name IS 'ชื่อหมวดย่อย';
COMMENT ON COLUMN acct.item_subcategories.subcategory_code IS 'subcategory code';
COMMENT ON COLUMN acct.item_subcategories.subcategory_name_en IS 'subcategory name en';
COMMENT ON COLUMN acct.item_subcategories.description_th IS 'description th';
COMMENT ON COLUMN acct.item_subcategories.display_order IS 'display order';
COMMENT ON COLUMN acct.item_subcategories.is_active IS 'ใช้งานอยู่ (false = ปิดใช้งาน ไม่แสดงในรายการเลือก)';
COMMENT ON TABLE acct.items IS 'สินค้า/บริการ — ใช้ในทุกเอกสารขาย/ซื้อ ผูกบัญชีรายได้/ค่าใช้จ่ายได้';
COMMENT ON COLUMN acct.items.item_id IS 'รหัส (Primary Key)';
COMMENT ON COLUMN acct.items.item_code IS 'รหัสสินค้า/บริการ (ห้ามซ้ำ)';
COMMENT ON COLUMN acct.items.item_name IS 'ชื่อสินค้า/บริการ';
COMMENT ON COLUMN acct.items.item_type IS 'GOODS = สินค้า, SERVICE = บริการ';
COMMENT ON COLUMN acct.items.unit IS 'หน่วยนับ';
COMMENT ON COLUMN acct.items.default_price IS 'ราคาขายเริ่มต้น';
COMMENT ON COLUMN acct.items.vat_type IS 'VAT / NON_VAT / ZERO_RATE / EXEMPT';
COMMENT ON COLUMN acct.items.revenue_account_id IS 'บัญชีรายได้ (→ chart_of_account_details)';
COMMENT ON COLUMN acct.items.expense_account_id IS 'บัญชีค่าใช้จ่าย (→ chart_of_account_details)';
COMMENT ON COLUMN acct.items.subcategory_id IS 'อ้างอิง → item_subcategories';
COMMENT ON COLUMN acct.items.created_at IS 'เวลาที่สร้างรายการ';
COMMENT ON COLUMN acct.items.created_by IS 'ผู้สร้างรายการ (username)';
COMMENT ON COLUMN acct.items.updated_at IS 'เวลาที่แก้ไขล่าสุด';
COMMENT ON COLUMN acct.items.updated_by IS 'ผู้แก้ไขล่าสุด (username)';
COMMENT ON COLUMN acct.items.is_active IS 'ใช้งานอยู่ (false = ปิดใช้งาน ไม่แสดงในรายการเลือก)';
COMMENT ON TABLE acct.journal_entries IS 'หัวรายการสมุดรายวัน (journal) — ผูกเอกสารต้นทางผ่าน ref_doc_type/ref_doc_no';
COMMENT ON COLUMN acct.journal_entries.journal_id IS 'รหัส (Primary Key)';
COMMENT ON COLUMN acct.journal_entries.journal_no IS 'เลขที่ JV-YYYYMMDD-NNNNN';
COMMENT ON COLUMN acct.journal_entries.journal_date IS 'วันที่ลงบัญชี (ถูกตรวจกับงวดบัญชี)';
COMMENT ON COLUMN acct.journal_entries.journal_type IS 'RECEIPT / PAYMENT / GENERAL / ADJUSTMENT';
COMMENT ON COLUMN acct.journal_entries.ref_doc_type IS 'ประเภทเอกสารต้นทาง';
COMMENT ON COLUMN acct.journal_entries.ref_doc_no IS 'เลขที่เอกสารต้นทาง';
COMMENT ON COLUMN acct.journal_entries.posted_flag IS 'true = นับในงบทดลอง';
COMMENT ON COLUMN acct.journal_entries.created_at IS 'เวลาที่สร้างรายการ';
COMMENT ON COLUMN acct.journal_entries.created_by IS 'ผู้สร้างรายการ (username)';
COMMENT ON COLUMN acct.journal_entries.updated_at IS 'เวลาที่แก้ไขล่าสุด';
COMMENT ON COLUMN acct.journal_entries.updated_by IS 'ผู้แก้ไขล่าสุด (username)';
COMMENT ON TABLE acct.journal_entry_lines IS 'บรรทัด debit/credit ของแต่ละ journal (ต้องสมดุลเสมอ)';
COMMENT ON COLUMN acct.journal_entry_lines.journal_line_id IS 'รหัสบรรทัด (PK)';
COMMENT ON COLUMN acct.journal_entry_lines.journal_id IS 'journal ที่ลงบัญชีของเอกสารนี้';
COMMENT ON COLUMN acct.journal_entry_lines.line_no IS 'ลำดับบรรทัด';
COMMENT ON COLUMN acct.journal_entry_lines.account_id IS 'บัญชี (→ chart_of_account_details)';
COMMENT ON COLUMN acct.journal_entry_lines.debit_amount IS 'ยอด Debit';
COMMENT ON COLUMN acct.journal_entry_lines.credit_amount IS 'ยอด Credit';
COMMENT ON TABLE acct.permissions IS 'รายการสิทธิ์ที่มีในระบบ (8 สิทธิ์)';
COMMENT ON COLUMN acct.permissions.perm_code IS 'รหัสสิทธิ์';
COMMENT ON COLUMN acct.permissions.perm_name IS 'คำอธิบายสิทธิ์';
COMMENT ON COLUMN acct.permissions.sort_order IS 'ลำดับแสดงผล';
COMMENT ON TABLE acct.po_items IS 'รายการในใบสั่งซื้อ';
COMMENT ON COLUMN acct.po_items.po_item_id IS 'รหัส (Primary Key)';
COMMENT ON COLUMN acct.po_items.po_id IS 'ใบสั่งซื้อ (→ purchase_orders)';
COMMENT ON COLUMN acct.po_items.item_id IS 'อ้างอิง → items';
COMMENT ON COLUMN acct.po_items.qty IS 'จำนวน';
COMMENT ON COLUMN acct.po_items.unit_price IS 'ราคาต่อหน่วย';
COMMENT ON COLUMN acct.po_items.amount IS 'จำนวนเงิน';
COMMENT ON TABLE acct.pr_items IS 'รายการในใบขอซื้อ';
COMMENT ON COLUMN acct.pr_items.pr_item_id IS 'รหัสรายการ (PK)';
COMMENT ON COLUMN acct.pr_items.pr_id IS 'อ้างอิง → purchase_requests';
COMMENT ON COLUMN acct.pr_items.item_id IS 'อ้างอิง → items';
COMMENT ON COLUMN acct.pr_items.qty IS 'จำนวน';
COMMENT ON COLUMN acct.pr_items.estimated_price IS 'ราคาประมาณการต่อหน่วย';
COMMENT ON TABLE acct.purchase_orders IS 'ใบสั่งซื้อ (PO) — สร้างจาก PR หรือสร้างตรง (pr_id = null)';
COMMENT ON COLUMN acct.purchase_orders.po_id IS 'รหัส (Primary Key)';
COMMENT ON COLUMN acct.purchase_orders.po_no IS 'เลขที่ PO-YYYYMMDD-NNNNN';
COMMENT ON COLUMN acct.purchase_orders.po_date IS 'วันที่ใบสั่งซื้อ';
COMMENT ON COLUMN acct.purchase_orders.vendor_id IS 'อ้างอิง → vendors';
COMMENT ON COLUMN acct.purchase_orders.pr_id IS 'ใบขอซื้อต้นทาง (ว่างได้)';
COMMENT ON COLUMN acct.purchase_orders.delivery_date IS 'วันที่ส่งของ/กำหนดส่ง';
COMMENT ON COLUMN acct.purchase_orders.status IS 'DRAFT / SENT / CONFIRMED / PARTIAL_RECEIVED / RECEIVED / CANCELLED';
COMMENT ON COLUMN acct.purchase_orders.vat_amount IS 'จำนวนเงินภาษีมูลค่าเพิ่ม';
COMMENT ON COLUMN acct.purchase_orders.total_amount IS 'ยอดรวมสุทธิ (รวม VAT)';
COMMENT ON COLUMN acct.purchase_orders.created_at IS 'เวลาที่สร้างรายการ';
COMMENT ON COLUMN acct.purchase_orders.created_by IS 'ผู้สร้างรายการ (username)';
COMMENT ON COLUMN acct.purchase_orders.updated_at IS 'เวลาที่แก้ไขล่าสุด';
COMMENT ON COLUMN acct.purchase_orders.updated_by IS 'ผู้แก้ไขล่าสุด (username)';
COMMENT ON COLUMN acct.purchase_orders.remark IS 'หมายเหตุ';
COMMENT ON COLUMN acct.purchase_orders.payment_term_text IS 'เงื่อนไขการชำระเงิน (ข้อความ)';
COMMENT ON COLUMN acct.purchase_orders.signature_mode IS 'โหมดลายเซ็นบนเอกสารพิมพ์: BLANK = เว้นว่าง, DIGITAL = ใส่ลายเซ็นดิจิทัล';
COMMENT ON TABLE acct.purchase_requests IS 'ใบขอซื้อ (PR)';
COMMENT ON COLUMN acct.purchase_requests.pr_id IS 'รหัส (Primary Key)';
COMMENT ON COLUMN acct.purchase_requests.pr_no IS 'เลขที่ PR-YYYYMMDD-NNNNN';
COMMENT ON COLUMN acct.purchase_requests.pr_date IS 'วันที่ใบขอซื้อ';
COMMENT ON COLUMN acct.purchase_requests.requested_by IS 'ผู้ขอซื้อ (→ employees)';
COMMENT ON COLUMN acct.purchase_requests.department IS 'แผนก';
COMMENT ON COLUMN acct.purchase_requests.status IS 'DRAFT / PENDING / APPROVED / REJECTED / CLOSED';
COMMENT ON COLUMN acct.purchase_requests.approved_by IS 'ผู้อนุมัติ (→ employees)';
COMMENT ON COLUMN acct.purchase_requests.created_at IS 'เวลาที่สร้างรายการ';
COMMENT ON COLUMN acct.purchase_requests.created_by IS 'ผู้สร้างรายการ (username)';
COMMENT ON COLUMN acct.purchase_requests.updated_at IS 'เวลาที่แก้ไขล่าสุด';
COMMENT ON COLUMN acct.purchase_requests.updated_by IS 'ผู้แก้ไขล่าสุด (username)';
COMMENT ON COLUMN acct.purchase_requests.remark IS 'หมายเหตุ';
COMMENT ON COLUMN acct.purchase_requests.signature_mode IS 'โหมดลายเซ็นบนเอกสารพิมพ์: BLANK = เว้นว่าง, DIGITAL = ใส่ลายเซ็นดิจิทัล';
COMMENT ON TABLE acct.quotation_categories IS 'หมวดใบเสนอราคา — ตัวรันเลขที่ใบเสนอราคาแยกตามหมวด (next_seq_no)';
COMMENT ON COLUMN acct.quotation_categories.category_code IS 'รหัสหมวด';
COMMENT ON COLUMN acct.quotation_categories.next_seq_no IS 'เลขลำดับถัดไปของหมวด';
COMMENT ON COLUMN acct.quotation_categories.category_name_th IS 'category name th';
COMMENT ON COLUMN acct.quotation_categories.category_name_en IS 'category name en';
COMMENT ON COLUMN acct.quotation_categories.is_active IS 'ใช้งานอยู่ (false = ปิดใช้งาน ไม่แสดงในรายการเลือก)';
COMMENT ON TABLE acct.quotation_items IS 'รายการสินค้า/บริการในใบเสนอราคา';
COMMENT ON COLUMN acct.quotation_items.quotation_item_id IS 'รหัส (Primary Key)';
COMMENT ON COLUMN acct.quotation_items.quotation_id IS 'อ้างอิง → quotations';
COMMENT ON COLUMN acct.quotation_items.item_id IS 'อ้างอิง → items';
COMMENT ON COLUMN acct.quotation_items.line_no IS 'ลำดับรายการ';
COMMENT ON COLUMN acct.quotation_items.description IS 'คำอธิบายรายการ (ว่าง = ใช้ชื่อสินค้า)';
COMMENT ON COLUMN acct.quotation_items.qty IS 'จำนวน';
COMMENT ON COLUMN acct.quotation_items.unit_price IS 'ราคาต่อหน่วย';
COMMENT ON COLUMN acct.quotation_items.amount IS 'จำนวนเงิน';
COMMENT ON TABLE acct.quotations IS 'ใบเสนอราคา — ต้นทางของใบส่งของ/ใบแจ้งหนี้';
COMMENT ON COLUMN acct.quotations.quotation_id IS 'รหัส (Primary Key)';
COMMENT ON COLUMN acct.quotations.quotation_no IS 'เลขที่ Q-{หมวด}-{ลำดับ}';
COMMENT ON COLUMN acct.quotations.category_id IS 'หมวดใบเสนอราคา (→ quotation_categories.category_code)';
COMMENT ON COLUMN acct.quotations.seq_no IS 'ลำดับในหมวด';
COMMENT ON COLUMN acct.quotations.quotation_date IS 'วันที่ใบเสนอราคา';
COMMENT ON COLUMN acct.quotations.customer_id IS 'อ้างอิง → customers';
COMMENT ON COLUMN acct.quotations.salesperson_id IS 'ผู้ขาย/ผู้ลงนาม (→ employees)';
COMMENT ON COLUMN acct.quotations.valid_until IS 'ยืนราคาถึงวันที่';
COMMENT ON COLUMN acct.quotations.status IS 'DRAFT / SENT / ACCEPTED / REJECTED / EXPIRED';
COMMENT ON COLUMN acct.quotations.customer_po_no IS 'เลขที่ใบสั่งซื้อของลูกค้า';
COMMENT ON COLUMN acct.quotations.customer_po_date IS 'วันที่ใบสั่งซื้อของลูกค้า';
COMMENT ON COLUMN acct.quotations.payment_term_text IS 'เงื่อนไขการชำระเงิน (ข้อความ)';
COMMENT ON COLUMN acct.quotations.subtotal_amount IS 'มูลค่าก่อน VAT';
COMMENT ON COLUMN acct.quotations.vat_amount IS 'จำนวนเงินภาษีมูลค่าเพิ่ม';
COMMENT ON COLUMN acct.quotations.total_amount IS 'ยอดรวมสุทธิ (รวม VAT)';
COMMENT ON COLUMN acct.quotations.created_by IS 'ผู้สร้างรายการ (username)';
COMMENT ON COLUMN acct.quotations.created_at IS 'เวลาที่สร้างรายการ';
COMMENT ON COLUMN acct.quotations.updated_at IS 'เวลาที่แก้ไขล่าสุด';
COMMENT ON COLUMN acct.quotations.updated_by IS 'ผู้แก้ไขล่าสุด (username)';
COMMENT ON TABLE acct.receipt_applications IS 'การจับคู่ใบเสร็จกับใบแจ้งหนี้ที่ชำระ (trigger ตรวจไม่ให้รับเกินยอดและอัปเดตสถานะใบแจ้งหนี้)';
COMMENT ON COLUMN acct.receipt_applications.receipt_application_id IS 'รหัส (PK)';
COMMENT ON COLUMN acct.receipt_applications.receipt_id IS 'อ้างอิง → receipts';
COMMENT ON COLUMN acct.receipt_applications.invoice_id IS 'อ้างอิง → invoices';
COMMENT ON COLUMN acct.receipt_applications.applied_amount IS 'จำนวนเงินที่ตัดชำระกับใบแจ้งหนี้';
COMMENT ON TABLE acct.receipt_items IS 'รายการสินค้า/บริการในใบเสร็จ (กรณี CASH_SALE)';
COMMENT ON COLUMN acct.receipt_items.receipt_item_id IS 'รหัสรายการ (PK)';
COMMENT ON COLUMN acct.receipt_items.receipt_id IS 'อ้างอิง → receipts';
COMMENT ON COLUMN acct.receipt_items.item_id IS 'อ้างอิง → items';
COMMENT ON COLUMN acct.receipt_items.qty IS 'จำนวน';
COMMENT ON COLUMN acct.receipt_items.unit_price IS 'ราคาต่อหน่วย';
COMMENT ON COLUMN acct.receipt_items.amount IS 'จำนวนเงิน';
COMMENT ON TABLE acct.receipts IS 'ใบเสร็จรับเงิน — CREDIT_COLLECTION (รับชำระตามใบแจ้งหนี้) หรือ CASH_SALE (ขายสด)';
COMMENT ON COLUMN acct.receipts.receipt_id IS 'รหัส (Primary Key)';
COMMENT ON COLUMN acct.receipts.receipt_no IS 'เลขที่ RC-YYYYMMDD-NNNNN';
COMMENT ON COLUMN acct.receipts.tax_invoice_no IS 'เลขที่ใบกำกับภาษี (กรณีขายสด)';
COMMENT ON COLUMN acct.receipts.receipt_date IS 'วันที่รับเงิน';
COMMENT ON COLUMN acct.receipts.customer_id IS 'อ้างอิง → customers';
COMMENT ON COLUMN acct.receipts.billing_note_id IS 'ใบวางบิลอ้างอิง';
COMMENT ON COLUMN acct.receipts.sale_type IS 'CREDIT_COLLECTION / CASH_SALE';
COMMENT ON COLUMN acct.receipts.payment_method IS 'CASH / TRANSFER / CHEQUE / CREDIT_CARD';
COMMENT ON COLUMN acct.receipts.amount_received IS 'ยอดรับชำระรวมก่อนหักภาษี';
COMMENT ON COLUMN acct.receipts.wht_amount IS 'จำนวนภาษีหัก ณ ที่จ่าย';
COMMENT ON COLUMN acct.receipts.net_amount IS 'ยอดสุทธิหลังหักภาษี ณ ที่จ่าย';
COMMENT ON COLUMN acct.receipts.posted_flag IS 'ลงบัญชี (Post to GL) แล้วหรือยัง';
COMMENT ON COLUMN acct.receipts.signature_mode IS 'โหมดลายเซ็นบนเอกสารพิมพ์: BLANK = เว้นว่าง, DIGITAL = ใส่ลายเซ็นดิจิทัล';
COMMENT ON COLUMN acct.receipts.created_at IS 'เวลาที่สร้างรายการ';
COMMENT ON COLUMN acct.receipts.created_by IS 'ผู้สร้างรายการ (username)';
COMMENT ON COLUMN acct.receipts.updated_at IS 'เวลาที่แก้ไขล่าสุด';
COMMENT ON COLUMN acct.receipts.updated_by IS 'ผู้แก้ไขล่าสุด (username)';
COMMENT ON COLUMN acct.receipts.cheque_no IS 'เลขที่เช็ค';
COMMENT ON COLUMN acct.receipts.bank_name IS 'ชื่อธนาคาร (ข้อความ — เลือกจาก Master Data → Banks)';
COMMENT ON COLUMN acct.receipts.payment_ref_date IS 'วันที่ตามเช็ค/โอน';
COMMENT ON COLUMN acct.receipts.wht_rate IS 'อัตราภาษีหัก ณ ที่จ่าย (%)';
COMMENT ON TABLE acct.role_permissions IS 'การกำหนดสิทธิ์ต่อบทบาท (role × permission) — ADMIN แก้ได้จากหน้า Settings';
COMMENT ON COLUMN acct.role_permissions.role_code IS 'บทบาท (ADMIN / ACCOUNTANT / SALES / VIEWER)';
COMMENT ON COLUMN acct.role_permissions.perm_code IS 'รหัสสิทธิ์';
COMMENT ON COLUMN acct.role_permissions.allowed IS 'อนุญาต (true) หรือไม่';
COMMENT ON COLUMN acct.role_permissions.updated_by IS 'ผู้แก้ไขล่าสุด (username)';
COMMENT ON COLUMN acct.role_permissions.updated_at IS 'เวลาที่แก้ไขล่าสุด';
COMMENT ON TABLE acct.setting IS 'ค่าตั้งค่าระบบแบบ key/value';
COMMENT ON COLUMN acct.setting.setting_key IS 'ชื่อค่าตั้งค่า (PK)';
COMMENT ON COLUMN acct.setting.setting_value IS 'ค่า';
COMMENT ON COLUMN acct.setting.description IS 'คำอธิบาย';
COMMENT ON COLUMN acct.setting.updated_at IS 'เวลาที่แก้ไขล่าสุด';
COMMENT ON COLUMN acct.setting.updated_by IS 'ผู้แก้ไขล่าสุด (username)';
COMMENT ON TABLE acct.shareholders IS 'ทะเบียนผู้ถือหุ้น — จำนวนหุ้นที่จอง มูลค่าหุ้น (อ้างอิงพนักงานได้)';
COMMENT ON COLUMN acct.shareholders.sh_id IS 'รหัส (Primary Key)';
COMMENT ON COLUMN acct.shareholders.sh_code IS 'รหัสผู้ถือหุ้น';
COMMENT ON COLUMN acct.shareholders.sh_name IS 'ชื่อผู้ถือหุ้น';
COMMENT ON COLUMN acct.shareholders.id_no IS 'เลขบัตรประชาชน/เลขนิติบุคคล';
COMMENT ON COLUMN acct.shareholders.address IS 'ที่อยู่ (ไทย) เลขที่ หมู่ ซอย ถนน';
COMMENT ON COLUMN acct.shareholders.phone IS 'โทรศัพท์';
COMMENT ON COLUMN acct.shareholders.email IS 'อีเมล';
COMMENT ON COLUMN acct.shareholders.shares_subscribed IS 'จำนวนหุ้นที่จอง';
COMMENT ON COLUMN acct.shareholders.par_value IS 'มูลค่าหุ้นละ (บาท)';
COMMENT ON COLUMN acct.shareholders.subscribed_amount IS 'ทุนที่จอง = หุ้น × มูลค่า';
COMMENT ON COLUMN acct.shareholders.is_active IS 'ใช้งานอยู่ (false = ปิดใช้งาน ไม่แสดงในรายการเลือก)';
COMMENT ON COLUMN acct.shareholders.remark IS 'หมายเหตุ';
COMMENT ON COLUMN acct.shareholders.created_at IS 'เวลาที่สร้างรายการ';
COMMENT ON COLUMN acct.shareholders.created_by IS 'ผู้สร้างรายการ (username)';
COMMENT ON COLUMN acct.shareholders.updated_at IS 'เวลาที่แก้ไขล่าสุด';
COMMENT ON COLUMN acct.shareholders.updated_by IS 'ผู้แก้ไขล่าสุด (username)';
COMMENT ON COLUMN acct.shareholders.employee_id IS 'พนักงาน (→ employees)';
COMMENT ON TABLE acct.system_gl_mappings IS 'ผูกบัญชีควบคุมของระบบ (AR_CONTROL, AP_CONTROL, VAT_OUTPUT ฯลฯ) ที่ใช้ลงบัญชีอัตโนมัติ';
COMMENT ON COLUMN acct.system_gl_mappings.mapping_key IS 'ชื่อบัญชีควบคุม (PK)';
COMMENT ON COLUMN acct.system_gl_mappings.account_id IS 'บัญชีจริงในผังบัญชี';
COMMENT ON COLUMN acct.system_gl_mappings.description IS 'คำอธิบาย';
COMMENT ON TABLE acct.tax_filing_details IS 'รายการเอกสารอ้างอิงประกอบแบบยื่นภาษีแต่ละฉบับ';
COMMENT ON COLUMN acct.tax_filing_details.tax_filing_detail_id IS 'รหัส (PK)';
COMMENT ON COLUMN acct.tax_filing_details.tax_filing_id IS 'อ้างอิง → tax_filings';
COMMENT ON COLUMN acct.tax_filing_details.ref_doc_type IS 'ประเภทเอกสารต้นทาง';
COMMENT ON COLUMN acct.tax_filing_details.ref_doc_no IS 'เลขที่เอกสารต้นทาง';
COMMENT ON COLUMN acct.tax_filing_details.ref_party_tax_id IS 'เลขผู้เสียภาษีของคู่ค้า';
COMMENT ON COLUMN acct.tax_filing_details.tax_base_amount IS 'ฐานภาษี';
COMMENT ON COLUMN acct.tax_filing_details.tax_amount IS 'ภาษี';
COMMENT ON TABLE acct.tax_filings IS 'แบบยื่นภาษีรายเดือน (ภ.พ.30 / ภ.ง.ด.1 / 3 / 53)';
COMMENT ON COLUMN acct.tax_filings.tax_filing_id IS 'รหัส (Primary Key)';
COMMENT ON COLUMN acct.tax_filings.filing_type IS 'PP30 / PND1 / PND3 / PND53';
COMMENT ON COLUMN acct.tax_filings.filing_period_month IS 'เดือนภาษี';
COMMENT ON COLUMN acct.tax_filings.filing_period_year IS 'ปีภาษี';
COMMENT ON COLUMN acct.tax_filings.filing_date IS 'วันที่ยื่น';
COMMENT ON COLUMN acct.tax_filings.due_date IS 'วันครบกำหนดชำระ';
COMMENT ON COLUMN acct.tax_filings.total_output_vat IS 'ภาษีขายรวม';
COMMENT ON COLUMN acct.tax_filings.total_input_vat IS 'ภาษีซื้อรวม';
COMMENT ON COLUMN acct.tax_filings.net_vat_payable IS 'ภาษีที่ต้องชำระสุทธิ';
COMMENT ON COLUMN acct.tax_filings.total_wht_amount IS 'ภาษีหัก ณ ที่จ่ายรวม';
COMMENT ON COLUMN acct.tax_filings.status IS 'DRAFT / SUBMITTED / PAID';
COMMENT ON COLUMN acct.tax_filings.created_at IS 'เวลาที่สร้างรายการ';
COMMENT ON COLUMN acct.tax_filings.created_by IS 'ผู้สร้างรายการ (username)';
COMMENT ON COLUMN acct.tax_filings.updated_at IS 'เวลาที่แก้ไขล่าสุด';
COMMENT ON COLUMN acct.tax_filings.updated_by IS 'ผู้แก้ไขล่าสุด (username)';
COMMENT ON TABLE acct.tax_rates IS 'อัตราภาษี (VAT / หัก ณ ที่จ่าย) ตามช่วงเวลาที่มีผล';
COMMENT ON COLUMN acct.tax_rates.tax_rate_id IS 'รหัส (Primary Key)';
COMMENT ON COLUMN acct.tax_rates.tax_code IS 'รหัสอัตราภาษี';
COMMENT ON COLUMN acct.tax_rates.tax_name IS 'ชื่ออัตราภาษี';
COMMENT ON COLUMN acct.tax_rates.tax_type IS 'VAT / WHT';
COMMENT ON COLUMN acct.tax_rates.rate_percent IS 'อัตรา (%)';
COMMENT ON COLUMN acct.tax_rates.effective_date IS 'วันที่เริ่มมีผล';
COMMENT ON TABLE acct.th_district IS 'อำเภอ/เขต (ข้อมูลอ้างอิง)';
COMMENT ON COLUMN acct.th_district.district_id IS 'รหัส (Primary Key)';
COMMENT ON COLUMN acct.th_district.district_name_th IS 'ชื่ออำเภอ/เขต (ไทย)';
COMMENT ON COLUMN acct.th_district.district_name_en IS 'ชื่ออำเภอ/เขต (อังกฤษ)';
COMMENT ON COLUMN acct.th_district.province_id IS 'อ้างอิง → th_province';
COMMENT ON TABLE acct.th_province IS 'จังหวัด (ข้อมูลอ้างอิง 77 จังหวัด)';
COMMENT ON COLUMN acct.th_province.province_id IS 'รหัส (Primary Key)';
COMMENT ON COLUMN acct.th_province.province_name_th IS 'ชื่อจังหวัด (ไทย)';
COMMENT ON COLUMN acct.th_province.province_name_en IS 'ชื่อจังหวัด (อังกฤษ)';
COMMENT ON TABLE acct.th_subdistrict IS 'ตำบล/แขวง พร้อมรหัสไปรษณีย์ (ข้อมูลอ้างอิง)';
COMMENT ON COLUMN acct.th_subdistrict.subdistrict_id IS 'รหัส (Primary Key)';
COMMENT ON COLUMN acct.th_subdistrict.subdistrict_name_th IS 'ชื่อตำบล/แขวง (ไทย)';
COMMENT ON COLUMN acct.th_subdistrict.subdistrict_name_en IS 'ชื่อตำบล/แขวง (อังกฤษ)';
COMMENT ON COLUMN acct.th_subdistrict.zip_code IS 'รหัสไปรษณีย์';
COMMENT ON COLUMN acct.th_subdistrict.district_id IS 'อ้างอิง → th_district';
COMMENT ON TABLE acct.vendor_credit_notes IS 'ใบลดหนี้ผู้ขาย — ลดยอดใบแจ้งหนี้ผู้ขายที่ลงบัญชีแล้ว';
COMMENT ON COLUMN acct.vendor_credit_notes.vcn_id IS 'รหัส (PK)';
COMMENT ON COLUMN acct.vendor_credit_notes.vcn_no IS 'เลขที่ภายใน VCN-YYYYMMDD-NNNNN';
COMMENT ON COLUMN acct.vendor_credit_notes.vendor_cn_no IS 'เลขที่ใบลดหนี้ของผู้ขาย (ห้ามซ้ำต่อผู้ขาย)';
COMMENT ON COLUMN acct.vendor_credit_notes.cn_date IS 'วันที่ใบลดหนี้';
COMMENT ON COLUMN acct.vendor_credit_notes.vi_id IS 'อ้างอิง → vendor_invoices';
COMMENT ON COLUMN acct.vendor_credit_notes.vendor_id IS 'อ้างอิง → vendors';
COMMENT ON COLUMN acct.vendor_credit_notes.reason IS 'เหตุผล';
COMMENT ON COLUMN acct.vendor_credit_notes.expense_account_id IS 'บัญชีค่าใช้จ่าย (→ chart_of_account_details)';
COMMENT ON COLUMN acct.vendor_credit_notes.subtotal IS 'มูลค่าก่อน VAT';
COMMENT ON COLUMN acct.vendor_credit_notes.vat_rate IS 'อัตรา VAT (%)';
COMMENT ON COLUMN acct.vendor_credit_notes.vat_amount IS 'จำนวนเงินภาษีมูลค่าเพิ่ม';
COMMENT ON COLUMN acct.vendor_credit_notes.total_amount IS 'ยอดรวมสุทธิ (รวม VAT)';
COMMENT ON COLUMN acct.vendor_credit_notes.vat_claim IS 'ขอคืนภาษีซื้อได้ (true) หรือไม่ได้ (false = รวม VAT เป็นค่าใช้จ่าย)';
COMMENT ON COLUMN acct.vendor_credit_notes.status IS 'ACTIVE / VOID';
COMMENT ON COLUMN acct.vendor_credit_notes.void_reason IS 'เหตุผลที่ยกเลิกเอกสาร';
COMMENT ON COLUMN acct.vendor_credit_notes.posted_flag IS 'ลงบัญชี (Post to GL) แล้วหรือยัง';
COMMENT ON COLUMN acct.vendor_credit_notes.journal_id IS 'journal ที่ลงบัญชีของเอกสารนี้';
COMMENT ON COLUMN acct.vendor_credit_notes.reversal_journal_id IS 'journal กลับรายการ (เมื่อยกเลิกเอกสารที่ลงบัญชีแล้ว)';
COMMENT ON COLUMN acct.vendor_credit_notes.signature_mode IS 'โหมดลายเซ็นบนเอกสารพิมพ์: BLANK = เว้นว่าง, DIGITAL = ใส่ลายเซ็นดิจิทัล';
COMMENT ON COLUMN acct.vendor_credit_notes.remark IS 'หมายเหตุ';
COMMENT ON COLUMN acct.vendor_credit_notes.created_at IS 'เวลาที่สร้างรายการ';
COMMENT ON COLUMN acct.vendor_credit_notes.created_by IS 'ผู้สร้างรายการ (username)';
COMMENT ON COLUMN acct.vendor_credit_notes.updated_at IS 'เวลาที่แก้ไขล่าสุด';
COMMENT ON COLUMN acct.vendor_credit_notes.updated_by IS 'ผู้แก้ไขล่าสุด (username)';
COMMENT ON TABLE acct.vendor_invoices IS 'ใบแจ้งหนี้/ใบกำกับภาษีผู้ขาย (AP) — แหล่งข้อมูลภาษีซื้อ';
COMMENT ON COLUMN acct.vendor_invoices.vi_id IS 'รหัส (Primary Key)';
COMMENT ON COLUMN acct.vendor_invoices.vi_no IS 'เลขที่ภายใน AP-YYYYMMDD-NNNNN';
COMMENT ON COLUMN acct.vendor_invoices.vendor_invoice_no IS 'เลขที่ใบแจ้งหนี้/ใบกำกับภาษีของผู้ขาย';
COMMENT ON COLUMN acct.vendor_invoices.invoice_date IS 'วันที่ใบแจ้งหนี้';
COMMENT ON COLUMN acct.vendor_invoices.due_date IS 'วันครบกำหนดชำระ';
COMMENT ON COLUMN acct.vendor_invoices.vendor_id IS 'อ้างอิง → vendors';
COMMENT ON COLUMN acct.vendor_invoices.po_id IS 'ใบสั่งซื้ออ้างอิง';
COMMENT ON COLUMN acct.vendor_invoices.description IS 'รายละเอียด';
COMMENT ON COLUMN acct.vendor_invoices.subtotal IS 'มูลค่าก่อน VAT';
COMMENT ON COLUMN acct.vendor_invoices.vat_rate IS 'อัตรา VAT (%)';
COMMENT ON COLUMN acct.vendor_invoices.vat_amount IS 'จำนวนเงินภาษีมูลค่าเพิ่ม';
COMMENT ON COLUMN acct.vendor_invoices.total_amount IS 'ยอดรวมสุทธิ (รวม VAT)';
COMMENT ON COLUMN acct.vendor_invoices.vat_claim IS 'ขอคืนภาษีซื้อได้ (true) หรือไม่ได้ (false = รวม VAT เป็นค่าใช้จ่าย)';
COMMENT ON COLUMN acct.vendor_invoices.status IS 'UNPAID / PARTIAL / PAID / VOID';
COMMENT ON COLUMN acct.vendor_invoices.void_reason IS 'เหตุผลที่ยกเลิกเอกสาร';
COMMENT ON COLUMN acct.vendor_invoices.remark IS 'หมายเหตุ';
COMMENT ON COLUMN acct.vendor_invoices.created_by IS 'ผู้สร้างรายการ (username)';
COMMENT ON COLUMN acct.vendor_invoices.created_at IS 'เวลาที่สร้างรายการ';
COMMENT ON COLUMN acct.vendor_invoices.updated_by IS 'ผู้แก้ไขล่าสุด (username)';
COMMENT ON COLUMN acct.vendor_invoices.updated_at IS 'เวลาที่แก้ไขล่าสุด';
COMMENT ON COLUMN acct.vendor_invoices.expense_account_id IS 'บัญชีค่าใช้จ่าย (→ chart_of_account_details)';
COMMENT ON COLUMN acct.vendor_invoices.posted_flag IS 'ลงบัญชี (Post to GL) แล้วหรือยัง';
COMMENT ON COLUMN acct.vendor_invoices.journal_id IS 'journal ที่ลงบัญชีของเอกสารนี้';
COMMENT ON COLUMN acct.vendor_invoices.reversal_journal_id IS 'journal กลับรายการ (เมื่อยกเลิกเอกสารที่ลงบัญชีแล้ว)';
COMMENT ON TABLE acct.vendor_payment_applications IS 'การจับคู่การจ่ายเงินกับใบแจ้งหนี้ผู้ขาย';
COMMENT ON COLUMN acct.vendor_payment_applications.vpa_id IS 'รหัส (PK)';
COMMENT ON COLUMN acct.vendor_payment_applications.vp_id IS 'อ้างอิง → vendor_payments';
COMMENT ON COLUMN acct.vendor_payment_applications.vi_id IS 'อ้างอิง → vendor_invoices';
COMMENT ON COLUMN acct.vendor_payment_applications.applied_amount IS 'จำนวนเงินที่ตัดชำระกับใบแจ้งหนี้';
COMMENT ON TABLE acct.vendor_payments IS 'การจ่ายเงินผู้ขาย — จ่ายตัดหลายใบแจ้งหนี้ได้ พร้อมหักภาษี ณ ที่จ่าย';
COMMENT ON COLUMN acct.vendor_payments.vp_id IS 'รหัส (Primary Key)';
COMMENT ON COLUMN acct.vendor_payments.vp_no IS 'เลขที่ PAY-YYYYMMDD-NNNNN';
COMMENT ON COLUMN acct.vendor_payments.pay_date IS 'วันที่จ่ายเงิน';
COMMENT ON COLUMN acct.vendor_payments.vendor_id IS 'อ้างอิง → vendors';
COMMENT ON COLUMN acct.vendor_payments.payment_method IS 'วิธีชำระเงิน';
COMMENT ON COLUMN acct.vendor_payments.cheque_no IS 'เลขที่เช็ค';
COMMENT ON COLUMN acct.vendor_payments.bank_name IS 'ชื่อธนาคาร (ข้อความ — เลือกจาก Master Data → Banks)';
COMMENT ON COLUMN acct.vendor_payments.ref_date IS 'วันที่ตามเช็ค/โอน';
COMMENT ON COLUMN acct.vendor_payments.gross_amount IS 'ยอดจ่ายก่อนหักภาษี';
COMMENT ON COLUMN acct.vendor_payments.wht_rate IS 'อัตราภาษีหัก ณ ที่จ่าย (%)';
COMMENT ON COLUMN acct.vendor_payments.wht_amount IS 'จำนวนภาษีหัก ณ ที่จ่าย';
COMMENT ON COLUMN acct.vendor_payments.net_amount IS 'ยอดสุทธิหลังหักภาษี ณ ที่จ่าย';
COMMENT ON COLUMN acct.vendor_payments.income_type IS 'ประเภทเงินได้ตามแบบ 50 ทวิ (1, 2, 3, 4A, 4B, 5, 6)';
COMMENT ON COLUMN acct.vendor_payments.income_desc IS 'รายละเอียดประเภทเงินได้';
COMMENT ON COLUMN acct.vendor_payments.wht_cert_id IS 'หนังสือ 50 ทวิ ที่ออกจากการจ่ายนี้';
COMMENT ON COLUMN acct.vendor_payments.status IS 'ACTIVE / VOID';
COMMENT ON COLUMN acct.vendor_payments.void_reason IS 'เหตุผลที่ยกเลิกเอกสาร';
COMMENT ON COLUMN acct.vendor_payments.remark IS 'หมายเหตุ';
COMMENT ON COLUMN acct.vendor_payments.signature_mode IS 'โหมดลายเซ็นบนเอกสารพิมพ์: BLANK = เว้นว่าง, DIGITAL = ใส่ลายเซ็นดิจิทัล';
COMMENT ON COLUMN acct.vendor_payments.created_by IS 'ผู้สร้างรายการ (username)';
COMMENT ON COLUMN acct.vendor_payments.created_at IS 'เวลาที่สร้างรายการ';
COMMENT ON COLUMN acct.vendor_payments.updated_by IS 'ผู้แก้ไขล่าสุด (username)';
COMMENT ON COLUMN acct.vendor_payments.updated_at IS 'เวลาที่แก้ไขล่าสุด';
COMMENT ON COLUMN acct.vendor_payments.posted_flag IS 'ลงบัญชี (Post to GL) แล้วหรือยัง';
COMMENT ON COLUMN acct.vendor_payments.journal_id IS 'journal ที่ลงบัญชีของเอกสารนี้';
COMMENT ON COLUMN acct.vendor_payments.reversal_journal_id IS 'journal กลับรายการ (เมื่อยกเลิกเอกสารที่ลงบัญชีแล้ว)';
COMMENT ON TABLE acct.vendors IS 'ผู้ขาย/เจ้าหนี้ — ฝั่งซื้อ (AP)';
COMMENT ON COLUMN acct.vendors.vendor_id IS 'รหัส (Primary Key)';
COMMENT ON COLUMN acct.vendors.vendor_code IS 'รหัสผู้ขาย (ห้ามซ้ำ) เช่น VEN-001';
COMMENT ON COLUMN acct.vendors.vendor_name_th IS 'ชื่อผู้ขาย (ไทย)';
COMMENT ON COLUMN acct.vendors.vendor_name_en IS 'ชื่อผู้ขาย (อังกฤษ)';
COMMENT ON COLUMN acct.vendors.tax_id IS 'เลขประจำตัวผู้เสียภาษี (13 หลัก)';
COMMENT ON COLUMN acct.vendors.branch_no IS 'รหัสสาขา (0000 = สำนักงานใหญ่)';
COMMENT ON COLUMN acct.vendors.address IS 'ที่อยู่ (ไทย) เลขที่ หมู่ ซอย ถนน';
COMMENT ON COLUMN acct.vendors.address_en IS 'ที่อยู่ (อังกฤษ)';
COMMENT ON COLUMN acct.vendors.subdistrict_id IS 'ตำบล/แขวง (→ th_subdistrict) — อำเภอ จังหวัดอ้างอิงต่อจากตำบล';
COMMENT ON COLUMN acct.vendors.zip_code IS 'รหัสไปรษณีย์';
COMMENT ON COLUMN acct.vendors.payment_term_days IS 'เครดิตเทอมที่ได้รับ (วัน)';
COMMENT ON COLUMN acct.vendors.created_at IS 'เวลาที่สร้างรายการ';
COMMENT ON COLUMN acct.vendors.created_by IS 'ผู้สร้างรายการ (username)';
COMMENT ON COLUMN acct.vendors.updated_at IS 'เวลาที่แก้ไขล่าสุด';
COMMENT ON COLUMN acct.vendors.updated_by IS 'ผู้แก้ไขล่าสุด (username)';
COMMENT ON COLUMN acct.vendors.phone IS 'โทรศัพท์';
COMMENT ON COLUMN acct.vendors.email IS 'อีเมล';
COMMENT ON COLUMN acct.vendors.contact_person IS 'ผู้ติดต่อ';
COMMENT ON COLUMN acct.vendors.is_active IS 'ใช้งานอยู่ (false = ปิดใช้งาน ไม่แสดงในรายการเลือก)';
COMMENT ON TABLE acct.wht_certificates IS 'หนังสือรับรองการหัก ณ ที่จ่าย (50 ทวิ) ที่บริษัทออกให้ผู้รับเงิน — 1 ใบ = 1 รายการเงินได้';
COMMENT ON COLUMN acct.wht_certificates.cert_id IS 'รหัส (Primary Key)';
COMMENT ON COLUMN acct.wht_certificates.cert_no IS 'เลขที่ WHT-YYYYMMDD-NNNNN';
COMMENT ON COLUMN acct.wht_certificates.book_no IS 'เล่มที่';
COMMENT ON COLUMN acct.wht_certificates.seq_no IS 'เลขที่ในเล่ม';
COMMENT ON COLUMN acct.wht_certificates.vendor_id IS 'อ้างอิง → vendors';
COMMENT ON COLUMN acct.wht_certificates.po_id IS 'ใบสั่งซื้อ (→ purchase_orders)';
COMMENT ON COLUMN acct.wht_certificates.form_type IS 'แบบ: PND1, PND1K, PND1K_SP, PND2, PND3, PND2K, PND3K, PND53';
COMMENT ON COLUMN acct.wht_certificates.form_seq IS 'ลำดับที่ในแบบ';
COMMENT ON COLUMN acct.wht_certificates.pay_date IS 'วันที่จ่ายเงิน';
COMMENT ON COLUMN acct.wht_certificates.income_type IS 'ประเภทเงินได้ตามแบบ 50 ทวิ (1, 2, 3, 4A, 4B, 5, 6)';
COMMENT ON COLUMN acct.wht_certificates.income_desc IS 'รายละเอียดประเภทเงินได้';
COMMENT ON COLUMN acct.wht_certificates.amount_paid IS 'จำนวนเงินที่จ่าย';
COMMENT ON COLUMN acct.wht_certificates.wht_rate IS 'อัตราภาษีหัก ณ ที่จ่าย (%)';
COMMENT ON COLUMN acct.wht_certificates.wht_amount IS 'จำนวนภาษีหัก ณ ที่จ่าย';
COMMENT ON COLUMN acct.wht_certificates.fund_gpf IS 'เงินสะสมกองทุน กบข.';
COMMENT ON COLUMN acct.wht_certificates.fund_sso IS 'เงินสมทบประกันสังคม';
COMMENT ON COLUMN acct.wht_certificates.fund_pvd IS 'เงินสะสมกองทุนสำรองเลี้ยงชีพ';
COMMENT ON COLUMN acct.wht_certificates.payer_mode IS 'ผู้จ่ายเงิน: WHT = หัก ณ ที่จ่าย, ALWAYS = ออกให้ตลอดไป, ONCE = ออกให้ครั้งเดียว, OTHER = อื่นๆ';
COMMENT ON COLUMN acct.wht_certificates.payer_other IS 'ระบุกรณี OTHER';
COMMENT ON COLUMN acct.wht_certificates.issue_date IS 'วันที่ออกหนังสือ';
COMMENT ON COLUMN acct.wht_certificates.status IS 'ISSUED / VOID';
COMMENT ON COLUMN acct.wht_certificates.void_reason IS 'เหตุผลที่ยกเลิกเอกสาร';
COMMENT ON COLUMN acct.wht_certificates.remark IS 'หมายเหตุ';
COMMENT ON COLUMN acct.wht_certificates.signature_mode IS 'โหมดลายเซ็นบนเอกสารพิมพ์: BLANK = เว้นว่าง, DIGITAL = ใส่ลายเซ็นดิจิทัล';
COMMENT ON COLUMN acct.wht_certificates.created_by IS 'ผู้สร้างรายการ (username)';
COMMENT ON COLUMN acct.wht_certificates.created_at IS 'เวลาที่สร้างรายการ';
COMMENT ON COLUMN acct.wht_certificates.updated_by IS 'ผู้แก้ไขล่าสุด (username)';
COMMENT ON COLUMN acct.wht_certificates.updated_at IS 'เวลาที่แก้ไขล่าสุด';
COMMENT ON VIEW acct.v_ar_aging IS 'อายุลูกหนี้การค้าคงค้าง แบ่งช่วง 0-30/31-60/61-90/90+ วัน นับจาก due_date';
COMMENT ON VIEW acct.v_dashboard_kpi IS 'ตัวเลขสรุปหน้า Dashboard — แถวเดียว (gl_unbalanced_count ควรเป็น 0)';
COMMENT ON VIEW acct.v_gl_trial_balance IS 'งบทดลองต่อบัญชี — นับเฉพาะ journal ที่ posted_flag = true';
COMMENT ON VIEW acct.v_invoice_balance IS 'ยอดชำระแล้ว/คงค้าง/ใบลดหนี้ ต่อใบแจ้งหนี้';
COMMENT ON VIEW acct.v_invoice_open IS 'ใบแจ้งหนี้ที่ยังชำระไม่เต็มจำนวน พร้อมจำนวนวันเกินกำหนด';
COMMENT ON VIEW acct.v_po_receipt_status IS 'ยอดสั่ง/ยอดรับสะสมต่อรายการใน PO';
COMMENT ON VIEW acct.v_quotation_open IS 'ใบเสนอราคาที่ยังไม่ปิดสถานะ';
COMMENT ON VIEW acct.v_shareholder_summary IS 'สรุปผู้ถือหุ้น: ยอดจอง ชำระแล้ว คงค้าง จำนวนครั้งที่ชำระ';
COMMENT ON VIEW acct.v_vi_balance IS 'ยอดจ่ายแล้ว/คงค้าง/ใบลดหนี้ ต่อใบแจ้งหนี้ผู้ขาย';
